//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procpu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcpupartmoudtl
    {
        public System.Guid transid { get; set; }
        public string partnerid { get; set; }
        public string partnername { get; set; }
        public string partneremail { get; set; }
        public string partnercnumber { get; set; }
        public System.Guid partnercountry { get; set; }
        public string partnermouupld { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public string delsts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lcm { get; set; }
    }
}
