//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procpu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcountrymast
    {
        public System.Guid transid { get; set; }
        public string country_name { get; set; }
        public string currency { get; set; }
        public string nationality { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public string del_sts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lum { get; set; }
        public string callcode { get; set; }
    }
}
