//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procpu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstdparentdtl
    {
        public System.Guid transid { get; set; }
        public System.Guid frmmodtransid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string idnumber { get; set; }
        public string email { get; set; }
        public string relation { get; set; }
        public string homeaddress { get; set; }
        public string mobile { get; set; }
        public string cname { get; set; }
        public string caddress { get; set; }
        public string suite { get; set; }
        public string state { get; set; }
        public string postalcode { get; set; }
        public string city { get; set; }
        public System.Guid cuntry { get; set; }
        public string cphno { get; set; }
        public string howdidyouhearaboutus { get; set; }
        public string fileupload { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public string delsts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lcm { get; set; }
    }
}
