//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procpu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstdapplicationdtl
    {
        public System.Guid transid { get; set; }
        public string stdfname { get; set; }
        public string stdmname { get; set; }
        public string stdlname { get; set; }
        public System.DateTime dob { get; set; }
        public string citizenship_id { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public System.Guid country { get; set; }
        public string phno { get; set; }
        public string grade { get; set; }
        public string subjectstaken { get; set; }
        public string pathway { get; set; }
        public string centrename { get; set; }
        public string centreaddress { get; set; }
        public string centrephno { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public string delsts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lum { get; set; }
    }
}
