//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procpu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstdacademicrecord
    {
        public System.Guid transid { get; set; }
        public Nullable<System.Guid> frmmodtransid { get; set; }
        public string coursetitle { get; set; }
        public Nullable<decimal> creditattempted { get; set; }
        public Nullable<decimal> creditearned { get; set; }
        public string finalgrade { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public string delsts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lum { get; set; }
        public Nullable<System.Guid> studenttransid { get; set; }
        public string assignments { get; set; }
        public string quizzes { get; set; }
        public string marksobtained { get; set; }
        public string totalmarks { get; set; }
    }
}
