//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procpu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstdacademicsummary
    {
        public System.Guid transid { get; set; }
        public Nullable<System.Guid> frmmodtransid { get; set; }
        public string cumugpa { get; set; }
        public Nullable<decimal> creditsattempted { get; set; }
        public Nullable<decimal> creditsearned { get; set; }
        public string diplomaearned { get; set; }
        public Nullable<System.DateTime> graduationdate { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public string delsts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lum { get; set; }
        public Nullable<System.Guid> studenttransid { get; set; }
        public string totalsubjects { get; set; }
        public string totalmarksattempted { get; set; }
        public string totalmarksobtained { get; set; }
        public string totalpercentage { get; set; }
    }
}
